/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package hr.algebra;

import hr.algebra.view.DragDropActorsPanel;
import hr.algebra.view.DragDropDirectors;
import hr.algebra.view.EditActorsPanel;
import hr.algebra.view.EditDirectorsPanel;
import hr.algebra.view.EditMoviePanel;

/**
 *
 * @author Korsnik
 */
public class MainWindow extends javax.swing.JFrame {

    
    /**
     * Creates new form MainWindow
     */
    public MainWindow() throws Exception {
        initComponents();
        initPanel();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane3 = new javax.swing.JTabbedPane();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(1050, 800));

        jTabbedPane3.setPreferredSize(new java.awt.Dimension(1240, 776));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTabbedPane jTabbedPane3;
    // End of variables declaration//GEN-END:variables

    private void initPanel() throws Exception {
        jTabbedPane3.add("Edit Movies", new EditMoviePanel());
        jTabbedPane3.add("Edit Directors", new EditDirectorsPanel());
        jTabbedPane3.add("Edit Actors", new EditActorsPanel());
        jTabbedPane3.add("DRAG&DROP ACTORS", new DragDropActorsPanel());
        jTabbedPane3.add("DRAG&DROP DIRECTORS", new DragDropDirectors());
        
    }

   
}
